[package]
name = "uuasm-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
divrem = "1.0.0"
leb128 = "0.2.5"
nom = "7.1.3"
nom_locate = "4.2.0"
