[workspace]
members = [".", "crates/wastjson-gen"]
resolver = "2"

[package]
name = "uuasm-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
divrem = "1.0.0"
leb128 = "0.2.5"
nom = "7.1.3"
nom_locate = "4.2.0"
rustix = { version = "0.38.14", features = ["mm"] }

[dev-dependencies]
serde = "1.0.197"
serde_json = "1.0.114"
