[package]
name = "uuasm-rt"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
num = "0.4.3"
thiserror = { workspace = true }
uuasm-ir = { workspace = true }
uuasm-codec = { workspace = true }
serde_json = "1.0.122"
