[package]
name = "uuasm-codec"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
num = "0.4.3"
paste = "1.0.15"
thiserror = { workspace = true }
uuasm-nodes = { workspace = true }
